aboutministry/urls.py
from django.urls import path
from . import views
app_name = 'aboutministry'
urlpatterns = [
    path('', views.about, name='about'),
]

announcements/urls.py
from django.urls import path
from . import views
app_name = 'announcements'
urlpatterns = [
    path('', views.announcements, name='announcements'),
]

contact/urls.py
from django.urls import path
from . import views
app_name = 'contact'
urlpatterns = [
    path('', views.contact, name='contact'),
]

days/urls.py
from django.urls import path
from . import views
app_name = 'days'
urlpatterns = [
    path('', views.days, name='days'),
]

events/urls.py
from django.urls import path
from .views import EventListView, EventDetailView

app_name = 'events'
urlpatterns = [
    # path('', EventListView.as_view(), name='event-list'),
    path('<pk>/', EventDetailView.as_view(), name='event-detail'),
]

gallery/urls.py
from django.urls import path
from . import views
app_name = 'gallery'
urlpatterns = [
    path('', views.gallery, name='gallery'),
]

home/urls.py
from django.urls import path
from . import views
# from .views import EventListView, EventDetailView
app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),
    # path('home', views.home, name='home'),
    path('aboutministry', views.about, name='about'),
    path('days', views.days, name='days'),
    path('contact', views.contact, name='contact'),
    path('announcements', views.announcements, name='announcements'),
    path('products', views.products, name='products'),
    path('gallery', views.gallery, name='gallery'),
    # path('event', EventListView.as_view(), name='event-list'),
    # path('<pk>/', EventDetailView.as_view(), name='event-detail'),
]

ministers/urls.py
from django.urls import path
from . import views
app_name = 'ministers'
urlpatterns = [
    path('', views.ministers, name='ministers'),
]

ministryapp/urls.py
from django.contrib import admin
# from django.conf.urls.defaults import *
from django.urls import path, include
from . import views

urlpatterns = [
    # path('', views.home),
    path('', include('home.urls')),
    # path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('aboutministry/', include('aboutministry.urls')),
    path('days/', include('days.urls')),
    path('contact/', include('contact.urls')),
    path('announcements/', include('announcements.urls')),
    path('events/', include('events.urls', namespace='events')),
    path('ministers/', include('ministers.urls')),
    path('products/', include('home.urls')),
    path('testimonies/', include('testimonies.urls')),
    path('gallery/', include('home.urls'))
]

testimonies/urls.py
from django.urls import path
from . import views
app_name = 'testimonies'
urlpatterns = [
    path('', views.testimonies, name='testimonies'),
]

contact/models.py
from django.db import models

# Create your models here.

days/models.py
from django.db import models

# Create your models here.

events/models.py
from django.db import models
from django.urls import reverse
# Create your models here.


class Event(models.Model):
    id = models.AutoField(primary_key=True)
    Event = models.CharField(blank=True, null=True, max_length=100)
    Date = models.DateTimeField()
    Details = models.TextField(
        max_length=500, blank=True, null=True)

    def __str__(self):
        return self.Event

    def get_absolute_url(self):
        return reverse("events:event-detail", kwargs={"pk": self.pk})

gallery/models.py
from django.db import models

# Create your models here.

ministers/models.py
from django.db import models

# Create your models here.

sermons/models.py
from django.db import models

# Create your models here.

contact/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
# Create your views here.


def contact(request):
    return render(request, 'contact.html')

days/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
# Create your views here.


def days(request):
    return render(request, 'days.html')

events/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Event


class EventListView(ListView):
    model = Event
    template_name = 'events/main.html'


class EventDetailView(DetailView):
    model = Event
    template_name = 'events/countdown.html'

gallery/views.py
from django.shortcuts import render


def gallery(request):
    return render(request, 'gallery.html')

home/views.py
from events.models import Event
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
from django.shortcuts import render


def home(request):
    events_list = Event.objects.all()
    return render(request, 'home.html', {'events': events_list})


def about(request):
    return render(request, 'about.html')


def days(request):
    return render(request, 'days.html')


def contact(request):
    return render(request, 'contact.html')


def announcements(request):
    return render(request, 'announcements.html')


def products(request):
    return render(request, 'products.html')


def gallery(request):
    return render(request, 'gallery.html')

ministers/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404
# Create your views here.


def ministers(request):
    return render(request, 'ministers.html')


ministryapp/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

sermons/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>DBSAM</title>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  
  {% load staticfiles %}
  <!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->
  <link href="{% static 'css/fontawesome-all.min.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'css/background-style.css' %}" rel="stylesheet" type="text/css" />
  <link href="{% static 'css/gallery.css' %}" rel="stylesheet"  />

  <!-- bootstrap js-->
  <!-- <script src="movies/bootstrap/js/bootstrap.js"></script> -->

  <style>
    body {
      font-size: 100%;
      overflow-x: hidden;
    }

    .nav2 {
      z-index: 10;
    }

    .hero {
      /* top: -62px !important; */
      height: 74vh;
      position: relative;
    }

    textarea {
      resize: none;
    }

    a{
      text-decoration: none !important;
    }
    .page-item {
      padding: 0px;
      font-size: 90%;
    }

    .powered span a:hover {
      color: skyblue !important;
    }

    .cover-for-detail{
      height: 60vh;
    }

    @media screen and (max-width:1024px) {
      .nav2 {
        width: 100% !important;
        /* margin: 0px !important; */
      }
    }

    @media screen and (max-width:425px) {
      body {
        font-size: 90% !important;
      }

      .navbar-collapse {
        padding: 8px;
      }

      .disclaimer {
        font-size: 0.623rem;
      }

      .powered {
        text-align: center !important;
        font-size: 0.8rem;
      }
    }
  </style>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light mb-0">
    <a class="navbar-brand ml-sm-4 font-weight-bold text-uppercase" href="{% url 'home:home' %}"><h3 class="m-0">DBSAM</h3> </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item mx-sm-3">
          <a class="nav-link" href="#"><i class="fa fa-phone"></i> 0801234567890</a>
        </li>
         <li class="nav-item mx-sm-3">
          <a class="nav-link" href="#"><i class="fa fa-at"></i> dbmonitsha@gmail.com</a>
        </li>
        <li class="nav-item mx-sm-3">
          <button class="btn btn-outline-success px-4" tabindex="-1" onclick="showDonate()">Donations</button>
        </li>
      </ul>
    </div>
  </nav>
  <main class=" container-fluid pb-5 px-0 mb-5 mt-0 pt-0">
    <nav class="navbar navbar-expand-lg rounded-0 mt-0 pt-0 navbar-light nav2">
      <div class="collapse navbar-collapse bg-white mx-auto mt-0 py-2 shadow-sm" id="navbarSupportedContent">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item mx-sm-4 active">
            <a class="nav-link link1" href="{% url 'home:home' %}">Home <span class="sr-only">(Current)</span></a>
          </li>
          <li class="nav-item mx-sm-3 text-capitalize">
            <a class="nav-link link2" href="{% url 'aboutministry:about' %}">About Us <span class="sr-only"></span></a>
          </li>
          <li class="nav-item mx-sm-3 text-capitalize">
            <a class="nav-link link3" href="{% url 'days:days' %}">Days of activities <span class="sr-only"></span></a>
          </li>
          <!-- <li class="nav-item mx-sm-3 text-capitalize">
            <a class="nav-link link4" href="#">Sermons <span class="sr-only"></span></a>
          </li> -->
          <!-- <li class="nav-item mx-sm-3 text-capitalize">
            <a class="nav-link link5" href="#">Gallery <span class="sr-only"></span></a>
          </li> -->
          <!-- <li class="nav-item mx-sm-3 text-capitalize">
            <a class="nav-link link6" href="#">Ministers <span class="sr-only"></span></a>
          </li> -->
          <li class="nav-item mx-sm-3 text-capitalize">
            <a class="nav-link link7" href="{% url 'contact:contact' %}">Contact <span class="sr-only"></span></a>
          </li>
          <li class="nav-item mx-sm-3 text-capitalize">
            <a class="nav-link link8" href="{% url 'announcements:announcements' %}">Announcements <span
                class="sr-only"></span></a>
          </li>

        </ul>
      </div>
    </nav>

    <div class="modal fade" id="donate_modal" tabindex="-1" role="dialog" aria-labelledby="donateModalLabel"
      aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="donateModalLabel">Donate to Dry Bone shall Rise Again Ministries</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
            <p>Our Ministry is on a heavenly mission to preach the gospel, bring deliverance in the
              name of Jesus Christ, set the captives free and
              improve the general wellbeing of the whole world through the gospel of Jesus Christ.<br><br>

              You can join our global cause by donating to the accounts below:<br>
              <span class="font-weight-bold">DBSAM International: 8683597307[Fidelity Bank] </span><br><br>
              <span class="font-weight-bold">DSAM Children Scholarship: 542625846547 [Access Bank] </span><br><br>
              <span class="font-weight-bold">DSAM Church Development: 635654727948 [Zenith Bank] </span><br><br>
            </p>

            <!-- <p>You can reach us by the numbers on our contact page or by calling 0812345677</p> -->
          </div>
          <div class="modal-footer">
            <h6 class="text-danger font-weight-normal">Do all online donations through the Account numbers provided on our website.<br>
              Note: Our ministers will NEVER
              call you to ask for money or ask for aid, report all
              suspicious actions on 08123456788</h6>
          </div>
        </div>
      </div>
    </div>
    {% block content %} {% endblock %}
  </main>


  <div class="jumbotron sticky-bottom bg-light rounded-0 m-0 col-12 p-1 d-flex flex-column justify-content-center align-items-center">
    <div class="col-sm-12">
      <div>
        <p class="mb-0 text-black text-center">
          © 2020 <span class="text-secondary">DBSAM</span>. All rights
          reserved
        </p>
        <p class="mb-0 text-secondary text-sm-right powered">
          Powered by
          <span><a class="text-dark" target="_blank"
              href="http://www.ParallelInfiniti.com">ParallelInfiniti.com</a></span>
        </p>
      </div>
    </div>
  </div>

  {% load static %}
  <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js.download' %}" type="text/javascript"></script>
  <script src="{% static 'js/script.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/main.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/gallery.js' %}" type="text/javascript"></script>
</body>

</html>

templates/home.html
{% extends 'base.html' %}

{% block content %}
<style>
  .box-mark {
    position: relative;
    left: -15px;
  }

  .boxes {
    cursor: pointer;
    transition: all 0.9s;
  }

  .boxes:hover {
    transform: scale(1.1);
    box-shadow: 2px 8px 20px black !important;
  }


  .box-home{
    display: none;
  }

  @media screen and (max-width:1024px) {
    .event-block {
      flex-wrap: wrap;
    }

    .upnext-con {
      /* border: 1px solid red; */
      border-bottom: 3px solid green;
      width: 100%;
      margin: 5px !important;
    }

    .detail-con {
      /* border: 1px solid red; */
      width: 45%;
      margin: 5px !important;
      text-align: center;
    }

    .timer-con {
      /* border: 1px solid red; */
      width: 55%;
      margin: 5px !important;
    }

    .timer-con .jumbotron {
      margin: 0px !important;
    }

    .all-events-con {
      /* border: 1px solid red; */
      width: 15%;
      margin: 5px !important;
    }
  }

  @media screen and (max-width:768px) {
    .upnext-con {
      width: 110%;
    }

    .detail-con {
      width: 55%;
    }

    .timer-con {
      width: 50%;
    }

    .timer-con .jumbotron {
      margin: 0px !important;
    }

    .all-events-con {
      width: 30%;
    }

    .row {
      width: 100% !important;
    }
  }

  @media screen and (max-width:425px) {

    .upnext-con {
      width: 110%;
    }

    .detail-con {
      width: 90%;
    }

    .timer-con {
      width: auto;
    }

    .timer-con .jumbotron {
      width: 100%;
      margin: 4px !important;
    }

    .all-events-con {
      width: auto;
    }

    .row {
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 5px;
      margin: 0px;
    }

    .row .jumbotron {
      width: 85%;
      margin-bottom: 40px !important;
    }

  }
</style>


<main class="container-fluid px-0">
  <div class="rounded-0 p-0 mb-0 mx-0 hero d-flex justify-content-center align-items-center">
    <div
      class="overlayed d-flex justify-content-center align-items-center d-flex justify-content-center align-items-center">
      <h1 class="font-italic font-weight-bold lead col-lg-8 col-md-8 text-light text-center text-capitalize" id="home-text"></h1>
    </div>
  </div>

  <div class="jumbotron rounded-0 mx-auto p-3 d-flex justify-content-center align-items-center event-block">
    {% for event in events %}
    <div class="d-flex justify-content-start align-items-center p-1 bg-transparent mx-sm-5">
      <i class="fab fa-user"></i>
      <div class="upnext-con">
        <span class="text-uppercase bg-success px-2 rounded-sm text-white">Next</span>
        <h6 class="text-uppercase m-0">Upcoming event</h6>
      </div>
    </div>

    <div class="bg-transparent mx-sm-5 p-1 detail-con">
      
      <div id="event-box" class="box-home">{{ event.Date|date:"M d, Y H:m:s"}}</div>
      <h4 class="mb-0">{{event.Event}}</h4>
      <span class="text-dark font-weight-normal fo1t-italic" >{{ event.Date|date:"D d, M, Y"}}</span>
    </div>

    <div class="bg-transparent mx-sm-5 p-1 d-flex justify-content-around align-items-center timer-con">
      <div class="jumbotron mx-sm-3 m-0 p-0 shadow-sm bg-white rounded-0">
        <div class="jumbotron p-1 m-0 rounded-0 bg-secondary">
          <p class="font-weight-bold m-0 text-center text-white" id="d-left-space"></p>
        </div>
        <div class="jumbotron p-0 px-1 m-0 rounded-0 bg-transparent"><span>Days</span></div>
      </div>
      <div class="jumbotron mx-sm-3 m-0 p-0 shadow-sm bg-white rounded-0">
        <div class="jumbotron p-1 m-0 rounded-0 bg-secondary">
          <p class="font-weight-bold m-0 text-center text-white" id="h-left-space"></p>
        </div>
        <div class="jumbotron p-0 px-1 m-0 rounded-0 bg-transparent"><span>Hours</span></div>
      </div>
      <div class="jumbotron mx-sm-3 m-0 p-0 shadow-sm bg-white rounded-0">
        <div class="jumbotron p-1 m-0 rounded-0 bg-secondary">
          <p class="font-weight-bold m-0 text-center text-white" id="m-left-space"></p>
        </div>
        <div class="jumbotron p-0 px-1 m-0 rounded-0 bg-transparent"><span>Mins</span></div>
      </div>
      <div class="jumbotron mx-sm-3 m-0 p-0 shadow-sm bg-white rounded-0">
        <div class="jumbotron p-1 m-0 rounded-0 bg-secondary">
          <p class="font-weight-bold m-0 text-center text-white"id="s-left-space" ></p>
        </div>
        <div class="jumbotron p-0 px-1 m-0 rounded-0 bg-transparent"><span>Secs</span></div>
      </div>
    </div>
    <div class="all-events-con">
        
      <a href="{{event.get_absolute_url}}" class="btn btn-outline-dark text-uppercase">See Event
          details</a>
    </div>
    
    {% endfor %}
  </div>

  <div class="row justify-content-center">
    <a href="{% url 'ministers:ministers' %}" class="jumbotron minister-box boxes bg-white border mx-sm-3 mb-0 px-2 py-2 col-lg-2 shadow-sm rounded-0 d-flex flex-column justify-content-end align-items-start"
      style="min-height: 250px;">
      <h5 class="m-0 bg-success text-white p-1 px-sm-3 box-mark">Our Ministers</h5>
    </a>

    <a href="{% url 'testimonies:testimonies' %}" class="jumbotron gallery-box boxes bg-white border mx-sm-3 mb-0 px-2 py-2 col-lg-2 shadow-sm rounded-0 d-flex
      flex-column justify-content-end align-items-start" style="min-height: 250px;">
      <h5 class="m-0 bg-success text-white p-1 px-sm-3 box-mark">Testimonies</h5>
    </a>
    <a href="{% url 'home:products' %}" class="jumbotron gallery-box boxes bg-white border mx-sm-3 mb-0 px-2 py-2 col-lg-2 shadow-sm rounded-0 d-flex
      flex-column justify-content-end align-items-start" style="min-height: 250px;">
      <h5 class="m-0 bg-success text-white p-1 px-sm-3 box-mark">our products</h5>
    </a>
    
    <a href="{% url 'home:gallery' %}" class="jumbotron sermon-box boxes bg-white border mx-sm-3 mb-0 px-2 py-2 col-lg-2 shadow-sm rounded-0 d-flex
      flex-column justify-content-end align-items-start" style="min-height: 250px;">
      <h5 class="m-0 bg-success text-white p-1 px-sm-3 box-mark">Gallery</h5>
    </a>
   
  </div>

</main>
{% endblock %}